hls format initialization time is infinity type
Chimeejs/chimee-helper-utils pull request #3
Opened 2019-12-04 09:15 UTC by mraiguo

2019-12-05 07:18 UTC, toxic-johann commented
没懂？为什么要改这里。

2019-12-05 07:38 UTC, mraiguo commented
@toxic-johann  播放hls的时候， 微信浏览器下一开始获取到的duration是infinity 如图：
![image](https://user-images.githubusercontent.com/22299421/70213689-eb53bc00-1774-11ea-860f-816b7e14863a.png)
我看了下源码吗，是在这里做时间展示的
![image](https://user-images.githubusercontent.com/22299421/70213712-00c8e600-1775-11ea-8bb0-48cb4c854003.png)
这时，要么在formatTime里判断处理，要么在这里判断处理，我选择在formatTime里面处理。  以上

2019-12-05 19:41 UTC, toxic-johann commented
为什么要返回空字符串？而不是类似 '--:--:--'

2019-12-06 02:05 UTC, mraiguo commented
@toxic-johann  如果觉得` --:--:--`更合适的话  那我改一下

2019-12-06 06:11 UTC, toxic-johann commented
现在更改后是什么效果？

2019-12-06 06:14 UTC, mraiguo commented
> 现在更改后是什么效果？

![image](https://user-images.githubusercontent.com/22299421/70300507-a726f100-1832-11ea-9eab-88b984cce9da.png)

2019-12-06 06:29 UTC, toxic-johann requested changes
A little change

2019-12-06 06:29 UTC, toxic-johann commented on src/index.js
> +  if (!window.isFinite(time)) {
Remove `window` here. It may be run in a non-browser environment.
```suggestion
  if (!isFinite(time)) {
```

2019-12-06 17:57 UTC, merged

2019-12-06 17:57 UTC, toxic-johann commented
I will publish this later, thanks so much~~